export const GET_PROFILE = 'GET_PROFILE';
export const GET_NEWS = 'GET_NEWS';

export const LOGIN_AUTHENTICATION='LOGIN_AUTHENTICATION';

export const GET_NEWSBYCATEGORY = 'GET_NEWSBYCATEGORY';
export const GET_NEWBYID = 'GET_NEWBYID';

